### ISSUE TITLE
Rubygems homepage link is dead, should be https://www.try-alf.org/

### ISSUE THREAD

**Issue by bshanks** [alf-tool/alf-doc#2]
https://rubygems.org/gems/alf has a link called "Homepage" which points to http://blambeau.github.com/alf which is a dead link. This should probably be updated to point to https://www.try-alf.org/ instead.

**Comment by llambeau** [comment]
Thanks @bshanks. We've fixed it. https://github.com/alf-tool/alf-doc/pull/3
